### ISSUE TITLE
Update action to use node16

### ISSUE THREAD

**Issue by sebastianst** [BetaHuhn/deploy-to-vercel-action#271]
Github [announced on 2022-09-22](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) that Actions are required to update to use node 16 instead of 12. Please update this action to node 16 🙏

Edit: this is already being worked on at #264

**Comment by urmauur** [comment]
+1

**Comment by bahrmichael** [comment]
@sebastianst @urmauur the PR has been merged :)

**Comment by sebastianst** [comment]
Awesome! Closed by #264
