### ISSUE TITLE
Stdout undefined. .trim error.

### ISSUE THREAD

**Issue by maxbec** [BetaHuhn/deploy-to-vercel-action#388]
**🐞 Describe the bug**

Discovered this bug today the first time:

<img width="1178" alt="image" src="https://github.com/BetaHuhn/deploy-to-vercel-action/assets/8254514/aeed1380-8f37-46ee-8062-35ca01a89188">

**Comment by abcfy2** [comment]
Same issue here. Please fix it.

**Comment by nicolassanmar** [comment]
@maxbec @abcfy2 Does anyone know why this might have happened?
It's weird that this started happening just now.
Maybe Vercel changed their API or github changed something about the runtime?

We might have to fix the issue ourselves as this looks unmaintained

**Comment by gwprice115** [comment]
same here

**Comment by wottpal** [comment]
@masonmcelvain Thanks for the fork & fixes! Just switched to `iFixit/deploy-to-vercel-action@master` and it works as it should :) 

@BetaHuhn Would love you to incorporate those and generally update the project & marketplace extension. Would be willed to sponsor the repo in return :)

**Comment by wottpal** [comment]
@BetaHuhn Just pushing this up :)
